apiVersion: v1
kind: Secret
metadata:
  name: meu-segredo
type: Opaque
data:
  usuario: YWRtaW4=        # admin (base64)
  senha: c2VuaGExMjM=      # senha123 (base64)
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-com-segredo
spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: USUARIO
          valueFrom:
            secretKeyRef:
              name: meu-segredo
              key: usuario
        - name: SENHA
          valueFrom:
            secretKeyRef:
              name: meu-segredo
              key: senha
