apiVersion: v1
kind: Pod
metadata:
  name: nginx-env
spec:
  containers:
    - name: nginx
      image: nginx:latest
      env:
        - name: AMBIENTE
          value: "desenvolvimento"
        - name: VERSAO
          value: "1.0.0"
