apiVersion: apps/v1
kind: Deployment
metadata:
  name: meu-deploy-com-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meu-app-com-service
  template:
    metadata:
      labels:
        app: meu-app-com-service
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80