apiVersion: v1
kind: Service
metadata:
  name: meu-service
spec:
  selector:
    app: meu-app-com-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      # nodePort: 30007
  type: ClusterIP # NodePort
