apiVersion: batch/v1
kind: CronJob
metadata:
  name: meu-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: meu-container
              image: busybox
              args:
                - /bin/sh
                - -c
                - echo "Executando CronJob a cada 5 minutos"
          restartPolicy: OnFailure
